### ISSUE TITLE
Chaussette does not work anymore with waitress v1.0.0

### ISSUE THREAD

**Issue by bbinet** [circus-tent/chaussette#82]
Here is the backtrace:

```
2016-09-13 14:35:42 [30] [INFO] Application is <bottle.Bottle object at 0x119d550>
2016-09-13 14:35:42 [30] [INFO] Serving on fd://9
2016-09-13 14:35:42 [30] [INFO] Using <class 'chaussette.backend._waitress.Server'> as a backend
Traceback (most recent call last):
  File "/usr/local/bin/chaussette", line 9, in <module>
    load_entry_point('chaussette==1.3.0', 'console_scripts', 'chaussette')()
  File "/usr/local/lib/python2.7/dist-packages/chaussette/server.py", line 224, in main
    inner()
  File "/usr/local/lib/python2.7/dist-packages/chaussette/server.py", line 205, in inner
    socket_type=_SOCKET_TYPE[args.socket_type])
  File "/usr/local/lib/python2.7/dist-packages/chaussette/server.py", line 38, in make_server
    server = server_class((host, port), app, **server_class_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chaussette/backend/_waitress.py", line 20, in __init__
    port=port)
  File "/usr/local/lib/python2.7/dist-packages/waitress/server.py", line 148, in __init__
    adj = Adjustments(**kw)
  File "/usr/local/lib/python2.7/dist-packages/waitress/adjustments.py", line 278, in __init__
    raise ValueError('Invalid host/port specified.')
ValueError: Invalid host/port specified.
```

Note that the same application is working well with waitress v0.9.0.

**Comment by narunask** [comment]
Confirmed:

```
2016-12-03 02:35:38 circus[7911] [INFO] Starting master on pid 7911
2016-12-03 02:35:38 circus[7911] [INFO] sockets started
2016-12-03 02:35:38 circus[7911] [INFO] Arbiter now waiting for commands
2016-12-03 02:35:38 circus[7911] [INFO] my_app started
2016-12-03 02:35:38 circus[7911] [INFO] circusd-stats started
2016-12-03 02:35:38 circus[7911] [INFO] circushttpd started
2016-12-03 02:35:38 circus[7919] [INFO] Starting the stats streamer
2016-12-03 02:35:38 circus-web[7920] [INFO] Starting circus web ui on fd 7
2016-12-03 02:35:38 [7918] [INFO] Application is <wheezy.http.application.WSGIApplication object at 0x7f532c4eac88>
2016-12-03 02:35:38 [7918] [INFO] Serving on fd://5
2016-12-03 02:35:38 [7918] [INFO] Using <class 'chaussette.backend._waitress.Server'> as a backend
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/waitress/adjustments.py", line 277, in __init__
    socket.AI_PASSIVE
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/chaussette", line 11, in <module>
    load_entry_point('chaussette==1.3.0', 'console_scripts', 'chaussette')()
  File "/usr/local/lib/python3.4/dist-packages/chaussette/server.py", line 224, in main
    inner()
  File "/usr/local/lib/python3.4/dist-packages/chaussette/server.py", line 205, in inner
    socket_type=_SOCKET_TYPE[args.socket_type])
  File "/usr/local/lib/python3.4/dist-packages/chaussette/server.py", line 38, in make_server
    server = server_class((host, port), app, **server_class_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/chaussette/backend/_waitress.py", line 20, in __init__
    port=port)
  File "/usr/local/lib/python3.4/dist-packages/waitress/server.py", line 155, in __init__
    adj = Adjustments(**kw)
  File "/usr/local/lib/python3.4/dist-packages/waitress/adjustments.py", line 297, in __init__
    raise ValueError('Invalid host/port specified.')
ValueError: Invalid host/port specified.
```
```
# pip3 freeze | egrep -i 'chau|wait'
chaussette==1.3.0
waitress==1.0.1
```

**Comment by douglatornell** [comment]
@evgeni  and @tarekziade thanks for this! I'm very happy to be able to unpin waitress==0.9.0.

**Comment by mrijken** [comment]
Please make a new release with this resolved issue.

**Comment by maparent** [comment]
FYI, I still have the same error with chaussette master. Using chaussette from circus, and waitress really seems not to like fd://123 endpoints. Out of curiosity, were your fixes tested with fd: endpoints? I only see IPv6 changes.
(Tried with waitress 1.0.0 and 1.0.2)
